# Site settings
title: Justing's blag
email: saps.laj@gmail.com
description: >
  Justing's (or sapslaj's) slightly less immature blog
  Now with fewer rants and grammatical errors
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sapslaj.github.io" # the base hostname & protocol for your site

socialmedia:
  twitter: https://twitter.com/sapslaj
  github: https://github.com/sapslaj
  youtube: https://www.youtube.com/user/sapslaj
  trello: https://trello.com/sapslaj
  reddit: https://www.reddit.com/user/sapslaj
  at: mailto:saps.laj@gmail.com

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# Build settings
markdown: redcarpet
highlighter: pygments
