# Site settings
title: Justing's blag
email: saps.laj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Justing's (or sapslaj's) slightly less immature blog
  Now with fewer rants and grammatical errors
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sapslaj.github.io" # the base hostname & protocol for your site

socialmedia:
  twitter: sapslaj
  github: sapslaj
  youtube: sapslaj
  trello: sapslaj


# Build settings
markdown: kramdown
